# -*- coding: utf-8 -*-
"""Email_gpt3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b9NGxLhcwloMx9PRSMC8Mwuy4yLjVsTa
"""

import openai

class email_generator:
        
    openai.api_key = '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'

    def generate_email(self, userPrompt =" professionall email", start="Dear" ,end="Yours sincerely"):
      

        response = openai.Completion.create(
        engine="davinci",
        prompt=userPrompt + "\n\n" + start,
        temperature=0.71,
        max_tokens=150,
        top_p=1,
        frequency_penalty=0.36,
        presence_penalty=0.75
        )
        return response.get("choices")[0]['text']

    def replace_spaces_with_pluses(self, sample):
        """Returns a string with each space being replaced with a plus so the email hyperlink can be formatted properly"""
        changed = list(sample)
        for i, c in enumerate(changed):
            if(c == ' ' or c =='  ' or c =='   ' or c=='\n' or c=='\n\n'):
                changed[i] = '+'
        return ''.join(changed)


